Text section for teams
tardis-sn/tardis-sn.github.io pull request #12
Opened 2021-08-23 13:37 UTC by KevinCawley

Adds the text for the teams section of the website
**Description**

Does all of the text, but leaves the grid and tables. 
**Motivation and context**

**How has this been tested?**
- [ ] Testing pipeline.
- [ ] Other. 

**Examples**

**Type of change**

- [ ] Bug fix. 
- [ ] New feature. 
- [ ] Breaking change. 
- [ ] None of the above. 

**Checklist**

- [ ] My change requires a change to the documentation.
    - [ ] I have updated the documentation accordingly.
    - [ ] (optional) I have built the documentation on my fork following [the instructions](https://tardis-sn.github.io/tardis/development/documentation_preview.html).
- [ ] I have assigned and requested two reviewers for this pull request.

2021-08-23 14:11 UTC, KevinCawley commented
https://kevincawley.github.io/tardis-sn.github.io/branch/teams_page/

2021-08-23 14:25 UTC, jaladh-singhal requested changes

2021-08-23 14:25 UTC, jaladh-singhal commented on content/team/community_roles.md
> + - Mentors for Google Summer of Code students
Remove them coz we have separate section for them below

2021-09-13 14:34 UTC, jaladh-singhal requested changes

2021-09-13 14:34 UTC, jaladh-singhal commented on content/team/collaboration.md
> +| GSoC 2014  | Vytautas Jančauskas   | No Report   |
It was under PSF - https://www.google-melange.com/archive/gsoc/2014/orgs/python/projects/bucket_brigade.html

2021-09-13 14:34 UTC, jaladh-singhal commented on content/team/collaboration.md
> +| GSoC 2020  | Jordi Eguren Brown   | <a href="https://summerofcode.withgoogle.com/archive/2020/projects/5699342318436352/" target="_blank" rel="noopener nofollow">TARDIS Code reestructure with facto
```suggestion
| GSoC 2020  | Jordi Eguren Brown   | <a href="https://summerofcode.withgoogle.com/archive/2020/projects/5699342318436352/" target="_blank" rel="noopener nofollow">TARDIS Code restructure with factory method</a>   |
```

2021-09-13 14:34 UTC, jaladh-singhal commented on content/team/collaboration.md
> +A brief explanation on GSoC & SoCIS
Can you please put a brief explaination of what GSoC and SoCIS are (hyperlinking them to their website)?

2021-09-13 14:34 UTC, jaladh-singhal commented on content/team/community_roles.md
> +</div>
Just write "Picture Grid (under construction)"

2021-09-24 14:33 UTC, jaladh-singhal approved these changes

2021-09-24 14:33 UTC, jaladh-singhal commented on content/team/collaboration.md
> +The Summer of Code In Space (SoCIS) is a program that aims at promoting open-source space-related software to students.
```suggestion
The [Google Summer of Code (GSoC)](https://summerofcode.withgoogle.com/) is a global program organized by Google where students work with an open source organization on a programming project during Summers. [Summer of Code In Space (SoCIS)](https://www.esa.int/Enabling_Support/Space_Engineering_Technology/SOCIS_The_ESA_Summer_of_Code_in_Space) is another similar program by ESA that aims at promoting open-source "space-related" software to students by letting them code new functionalities.
```

2021-09-24 14:33 UTC, jaladh-singhal commented on content/team/community_roles.md
> + This is in here as a placeholder!
```suggestion
Picture Grid of core team (under construction)
```

2021-09-24 14:35 UTC, merged