Filling out Papers Page
tardis-sn/tardis-sn.github.io pull request #20
Opened 2021-11-20 15:47 UTC by KevinCawley

Copied the Papers from the docs to the website. 
**Description**

Copied the papers from https://tardis-sn.github.io/tardis/research/research_done_using_TARDIS/research_papers.html 
to the papers page of the website.
**Motivation and context**

**How has this been tested?**
- [ ] Testing pipeline.
- [ ] Other. 

**Examples**

**Type of change**

- [ ] Bug fix. 
- [ ] New feature. 
- [ ] Breaking change. 
- [ ] None of the above. 

**Checklist**

- [ ] My change requires a change to the documentation.
    - [ ] I have updated the documentation accordingly.
    - [ ] (optional) I have built the documentation on my fork following [the instructions](https://tardis-sn.github.io/tardis/development/documentation_preview.html).
- [ ] I have assigned and requested two reviewers for this pull request.

2021-11-20 15:47 UTC, KevinCawley commented
https://kevincawley.github.io/tardis-sn.github.io/branch/papers/research/papers/

2021-11-22 13:12 UTC, jaladh-singhal requested changes
Looks neat - good to see that you've used markdown. There are few minor things

2021-11-22 13:12 UTC, jaladh-singhal commented on content/research/papers.md
> +## Papers Using Tardis
```suggestion
## Papers using *tardis* package
```

2021-11-22 13:12 UTC, jaladh-singhal commented on content/research/papers.md
> +**Kerzendorf, Wolfgang E., Sim, Stuart A.** 2014, MNRAS, *"A spectral synthesis code for rapid modelling of supernovae"* <a href="https://ui.adsabs.harvard.edu/abs/2014MNRAS.440..387K" target="_blank
Add section for carsus package and fill in with item no. 1 from here: https://tardis-sn.github.io/carsus/research/publications.html (no. 2 is actually a poster so we don't want it here)

2021-11-24 14:37 UTC, jaladh-singhal approved these changes

2021-11-24 14:37 UTC, jaladh-singhal commented on content/research/papers.md
> +## Papers using the *TARDIS* package
```suggestion
## Papers using the *tardis* package
```

2021-11-24 14:37 UTC, jaladh-singhal commented on content/research/papers.md
> +## Papers using the *CARSUS* package
```suggestion
## Papers using the *carsus* package
```

2021-11-24 14:38 UTC, merged