Add Credits Page
tardis-sn/tardis-sn.github.io pull request #4
Opened 2021-06-14 14:12 UTC by KevinCawley

Take the Credits and Publication policies page from the docs and add it here. 

**Description**

**Motivation and context**

**How has this been tested?**
- [ ] Testing pipeline.
- [ ] Other. 

**Examples**

**Type of change**

- [ ] Bug fix. 
- [ ] New feature. 
- [ ] Breaking change. 
- [ ] None of the above. 

**Checklist**

- [ ] My change requires a change to the documentation.
    - [ ] I have updated the documentation accordingly.
    - [ ] (optional) I have built the documentation on my fork following [the instructions](https://tardis-sn.github.io/tardis/development/documentation_preview.html).
- [ ] I have assigned and requested two reviewers for this pull request.

2021-06-14 18:51 UTC, KevinCawley commented
Right now the software isn't in bibtex quotes. This is because, right now, I am unsure if I will be including the contents or if it will be a link to a file with the information. I can make it in bibtex if we want to keep it as-is right now. However, that will be a commit.

2021-06-14 19:22 UTC, KevinCawley commented
@jaladh-singhal If you want, I can open a new PR that will only have 1 commit by doing `git fetch upstream` and `git checkout upstream/master`, and just modifying it again. I had made this branch by doing a checkout from the master!

2021-06-21 13:46 UTC, jaladh-singhal requested changes

2021-06-21 13:46 UTC, jaladh-singhal commented on content/credits.md
> +# Credits & Publication Policies
Remove this from here and put it in `title` instead (at L2)

2021-06-21 13:46 UTC, jaladh-singhal commented on content/credits.md
> +title: "Credits"
Change it to Credits & Publication Policies

2021-06-28 13:33 UTC, jaladh-singhal approved these changes

2021-06-28 13:34 UTC, merged