Added Title Metadata to TARDIS Website
tardis-sn/tardis-sn.github.io pull request #9
Opened 2021-07-04 08:02 UTC by DhruvSondhi

Updated the Meta Data to TARDIS Website to point to the correct values.

**Description**

**Motivation and context**

**How has this been tested?**
- [ ] Testing pipeline.
- [ ] Other. 

**Type of change**

- [ ] Bug fix. 
- [ ] New feature. 
- [ ] Breaking change. 
- [ ] None of the above. 

**Checklist**

- [ ] My change requires a change to the documentation.
    - [ ] I have updated the documentation accordingly.
    - [ ] (optional) I have built the documentation on my fork following [the instructions](https://tardis-sn.github.io/tardis/development/documentation_preview.html).
- [ ] I have assigned and requested two reviewers for this pull request.

2021-07-05 05:07 UTC, DhruvSondhi commented
**Preview here**: https://dhruvsondhi.github.io/tardis-sn.github.io/branch/title_metadata/

2021-07-06 13:38 UTC, jaladh-singhal requested changes

2021-07-06 13:38 UTC, jaladh-singhal commented on content/_index.md
> +  description: Website for TARDIS-SN
This is not how you describe something. Suppose you shared Numfocus website on twitter, it shouldn't say Website for NumFOCUS, right? :sweat_smile:

It instead describes what NumFOCUS is. Do the same for TARDIS for all 3 descriptions - you can use our twitter bio (https://twitter.com/tardis_sn)

2021-07-06 16:18 UTC, jaladh-singhal approved these changes

2021-07-06 16:18 UTC, jaladh-singhal commented on content/_index.md
> +  description: TARDIS is an open-source code to analyze observations of exploding stars. It is developed by a multi-disciplinary team.
```suggestion
  description: A community-developed tool to simulate the spectrum of light emitted by exploding stars using Monte Carlo techniques.
```

2021-07-06 16:18 UTC, jaladh-singhal commented on content/_index.md
> +      value: TARDIS is an open-source code to analyze observations of exploding stars. It is developed by a multi-disciplinary team.
```suggestion
      value: A community-developed tool to simulate the spectrum of light emitted by exploding stars using Monte Carlo techniques.
```

2021-07-06 16:18 UTC, jaladh-singhal commented on content/_index.md
> +      value: TARDIS is an open-source code to analyze observations of exploding stars. It is developed by a multi-disciplinary team.
```suggestion
      value: A community-developed tool to simulate the spectrum of light emitted by exploding stars using Monte Carlo techniques.
```

2021-07-06 16:19 UTC, merged